baseURL: "https://rishimo.github.io"
languageCode: "en-us"
title: "About Rishi"
theme: 
  - hugo-profile
  - hugo-shortcode-gallery

googleAnalytics: G-KGECC6G1HV

# add 5 minute timeout to allow gallery to build
timeout: 300000

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blogs
    #   weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hello!"
  description: Some stuff about me.
  # staticPath: ""  # The path to serve the static files from
  favicon: '/images/favicon.svg'

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    textColor: "#2171b5"
    secondaryTextColor: "#6baed6"
    backgroundColor: "F1F3FF"
    secondaryBackgroundColor: "#aaaaaa"
    primaryColor: "#2171b5"
    secondaryColor: "#eff3ff"

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Hi there!" # Brand name for the brand | default is the title variable
    disableSearch: true
    
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Rishi."
    subtitle: "I am a data science student,"
    content: | 
      and I'm passionate about *__engineering__*, *__photography__*, and *__making__* things.   
      I'm always looking for new ways to apply my technical skills and creativity to solve problems.

    image: '/images/rishi_lofi_outline_mini.svg'
    button:
      enable: true
      name: "Resume"
      url: "resume.pdf"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/rishimo
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/mohan-rishi
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/mohan_ocean_iso.png"
    content: |-
      I am currently a Master's in Data Science student at the [University of San Francisco](usfca.edu), working for [Metaphor Data](https://metaphor.io/) as a Machine Learning Engineer. 
      I did my bachelor's in industrial engineering at the [University of Illinois](https://grainger.illinois.edu), where I worked a lot with the [Illini Solar Car](https://illinisolarcar.com) team. ILL!

    skills:
      enable: true
      title: "Here are some things I have experience with."
      items:
        - "Python"
        - "Machine learning"
        - "Statistical modeling"
        - "Data analysis"
        - "R"
        - "SQL"
        - "Adobe Creative Suite"
        - "Prototyping & Manufacturing"


  # Experience
  experience:
    enable: false
    # title: "Custom Name"
    
    items:
      - job: "Operations Management Intern"
        company: "Eaton"
        companyUrl: "https://eaton.com"
        date: "May 2022 - Aug 2022"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I performed cycle time studies in a highly vertically-integrated manufacturing plant for Eaton's Vehicle Group. In addition to data collection, I analyzed plant output in the context of historical shifts in cycle times to calculate operating efficiencies of each line and machine group. I built a model to forecast true production output of a line given certain parameters based on this analysis.

      - job: "Alumni Coordinator"
        company: "Illini Solar Car"
        companyUrl: "https://illinisolarcar.com"
        date: "Aug 2019 - May 2023"
        featuredLink:
          enable: true
          name: "Learn about us!"
          url: "https://illinisolarcar.com"
        info:
          enable: false
          content: |
          I served as the team's Alumni Coordinator, helping make major operational and engineering decisions to further the design and racing of our next vehicle. I previously served as the Director of Operations (2021-2022) and Media Group Lead (2020-2021).

      - job: "Shop Supervisor"
        company: "Siebel Center for Design"
        companyUrl: "https://designcenter.illinois.edu"
        date: "Jan 2022 - May 2023"
        featuredLink:
          enable: true
          name: "The Shop"
          url: "https://designcenter.illinois.edu/thecenter/theshop"
        info:
          enable: false
          content: 
        content: |
          I worked as a student supervisor in the Shop makerspace at SCD. I helped develop policy for the space, led teams of 2-10 staff, and oversaw open-hours operations. I trained staff and guests on the operation of industry-standard prototyping & manufacturing equipment including a waterjet cutter, large format printer, laser cutters, and a full woodshop.

      
      - job: "Student Manager"
        company: "Illini Union"
        companyUrl: "https://union.illinois.edu"
        date: "August 2019 - November 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
        content: |
          I worked as a student technician for the Illini Union, becoming a trainer in January of 2020 and a student manager in 2021. I oversaw A/V setups ranging from projectors for conferences to audio engineering for large outdoor performance venues, directing teams of 3-5 technicians. I used tools including Allen&Heath soundboards, ETC lighting controls and fixtures, Audio-Technica and Shure microphone products, and JBL speaker solutions. 
      
  # Education
  education:
    enable: false
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Business Administration"
        school:
          name: "University of California, Berkeley"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Massachusetts Institute of Technology"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Thomas Jefferson High School for Science and Technology."
          url: "https://example.org"
        GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Jira implementation
        content: |
          Implementation, maintenance, and administration of VPS-based Jira instance for team of 200+.
          Using DigitalOcean cloud infrastructure, I developed a Jira instance for the Illini Solar Car team, and created trainings & workshops to run with group leads and team members ranging from the electrical group to the business group.
        image: /projects/JIRA.svg
        #featured:
        # name: Live!
        # link: https://jira.illinisolarcar.com
        badges:
          - "Networking"
          - "Scripting"
          - "Project Management"
        # links:
        #   - icon: fa fa-envelope
        #     url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/hugo-profile
        #   - icon: fab fa-twitter
        #     url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: STAT447 final project
        content: |
          A team-based deep-dive analysis and series of visualizations on the relationship between adult obesity rates and heart disease mortality rates in the contiguous 48 states, using data from the CDC. 
          I developed the choropleth maps and the associated data wrangling for the project, using the R statistical programming language via RStudio & GitHub for collaboration.
        image: /projects/STAT447.svg
        featured:
          name: Our report
          link: /projects/project-report.html
        badges:
          - "R"
          - "GitHub"
          - "ggplot2"
        links:
          - icon: fab fa-github
            url: https://github.com/illinois-stat447
          - icon: fab fa-font-awesome
            url: https://stat447.com

      - title: Senior Engineering Project
        content: |
          Team based senior capstone project. Our team developed a computer-vision based nondestructive testing methodology for ultrasonically welded cable harnesses manufactured by an industry partner. 
          Designed and assembled a testing frame including 2 machine vision cameras and a custom mounting system, wrote Python image capture and parse scripts, and performed extensive statistical analysis & modeling.
        image: /projects/SE494.svg
        # featured:
        #   name: Demo V2
        #   link: https://hugo-profile-2.netlify.app
        badges:
          - "Python"
          - "OpenCV"
          - "R"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: false
    # title: "Custom Name"
    content: 
    email: 
    btnName: Mail me

  footer:
    # recentPosts:
    #   path: "blogs"
    #   count: 3
    #   title: Recent Posts
    #   enable: true
    #   disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/rishimo
      linkedin: https://linkedin.com/in/mohan-rishi
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com
  
  imaging.exif:
    includeFields: ".*"

  # # List pages like blogs and posts
  # listPages:
  #   disableFeaturedImage: false